clc
printf("Amal Thundiyil - 2020400066 SE IT - D\n")
A = rand(4,4)
B = rand(4,4)
printf("The first random matrix is")
disp(A)
printf("The second random matrix is")
disp(B)
printf("The product of two matrices is")
disp(A*B)
printf("The sum of two matrices is")
disp(A+B)
